default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
  user: postgres
  password: postgres

development:
  <<: *default
  database: roogby_development

test:
  <<: *default
  database: roogby_test

production:
  <<: *default
  database: roogby_production